apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
        - name: paperless
          image: anabibovska/paperless-ngx:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: paperless-config
          env:
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_DBPASS
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: PAPERLESS_SECRET_KEY
          volumeMounts:
            - name: consume
              mountPath: /usr/src/paperless/consume
            - name: media
              mountPath: /usr/src/paperless/media
            - name: data
              mountPath: /usr/src/paperless/data
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: consume
          emptyDir: {}
        - name: media
          emptyDir: {}
        - name: data
          emptyDir: {}