apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: paperless
type: Opaque
stringData:
  POSTGRES_PASSWORD: "paperlesspassword"
  PAPERLESS_DBPASS: "paperlesspassword"
  PAPERLESS_SECRET_KEY: "change-this-secret-key"